# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "windows-8.1-enterprise-eval"
  config.vm.box_check_update = false

  config.vm.synced_folder "..", "/posh-vpn"

  config.vm.provider "virtualbox" do |provider|
    # Display the VirtualBox GUI when booting the machine
    provider.gui = true

    provider.cpus   = 1
    provider.memory = 1024
    provider.customize ['modifyvm', :id, '--clipboard',   'bidirectional' ]
    provider.customize ['modifyvm', :id, '--draganddrop', 'bidirectional' ]
  end

  # TODO: Add installation of AnyConnect
  # TODO: Add installation of posh-vpn
  # config.vm.provision "shell", inline: <<-SHELL
  #   sudo apt-get update
  #   sudo apt-get install -y apache2
  # SHELL
end
